### ISSUE TITLE
plugin is losing user context

### ISSUE THREAD

**Issue by acfi-network** [mangoweb-sylius/SyliusSortingPlugin#2]
Hello, thks for the plugin.
When i activate the plugin and routes, i get an error on the _security.html.twig
impossible to access user.
I am on sylius 1.5.1
Best regards
Mathieu

**Comment by ondrej-kuhnel** [comment]
Hi, 
you are probably outside of the admin firewall.
Have you added a routing with the prefix `admin`?

```
mango_sylius_sorting_plugin:
    resource: "@MangoSyliusSortingPlugin/Resources/config/routing.yml"
    prefix: /admin
```

**Comment by acfi-network** [comment]
Oh yes sorry, exactly that :)
Thanks for the quick reply ! This plugin is perfect !
